package com.app.golgo.auth.entity;

import static org.assertj.core.api.Assertions.assertThat;

import jakarta.persistence.GeneratedValue;
import java.lang.reflect.Field;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;

class AuthEntityIdGenerationTest {

	private static final Clock CLOCK = Clock.fixed(Instant.parse("2026-05-28T00:00:00Z"), ZoneOffset.UTC);

	@Test
	void authEntityIdsDoNotUseJpaUuidGeneration() throws NoSuchFieldException {
		List<Class<?>> entities = List.of(User.class, AuthProvider.class, RefreshToken.class);

		for (Class<?> entity : entities) {
			Field id = entity.getDeclaredField("id");

			assertThat(id.getAnnotation(GeneratedValue.class))
				.as(entity.getSimpleName() + ".id must be generated by database uuid_v7()")
				.isNull();
		}
	}

	@Test
	void localUserContainsLoginCredentialFields() {
		PasswordEncoder passwordEncoder = new BCryptPasswordEncoder();

		User user = User.createLocal(
			"golgo01",
			passwordEncoder.encode("Password!1"),
			"홍길동",
			"user@example.com",
			"투자초보",
			CLOCK
		);

		assertThat(user.getLoginId()).isEqualTo("golgo01");
		assertThat(user.getPasswordHash()).startsWith("$2");
		assertThat(user.getName()).isEqualTo("홍길동");
		assertThat(user.getEmail()).isEqualTo("user@example.com");
		assertThat(user.getNickname()).isEqualTo("투자초보");
	}
}
