package com.app.golgo.auth.domain;

import static org.assertj.core.api.Assertions.assertThat;

import jakarta.persistence.GeneratedValue;
import java.lang.reflect.Field;
import java.util.List;
import org.junit.jupiter.api.Test;

class AuthEntityIdGenerationTest {

	@Test
	void authEntityIdsDoNotUseJpaUuidGeneration() throws NoSuchFieldException {
		List<Class<?>> entities = List.of(User.class, AuthProvider.class, RefreshToken.class);

		for (Class<?> entity : entities) {
			Field id = entity.getDeclaredField("id");

			assertThat(id.getAnnotation(GeneratedValue.class))
				.as(entity.getSimpleName() + ".id must be generated by database uuid_v7()")
				.isNull();
		}
	}
}
