package com.app.golgo.analysis.entity;

public enum SectionCode {
	DATA_VERIFICATION,
	BUSINESS_MODEL,
	INDUSTRY_STRUCTURE,
	FINANCIALS,
	VALUATION,
	EARNINGS_CALL,
	MACRO_POLICY,
	CATALYSTS_AND_RISKS,
	ETF_ANALYSIS
}
